### ISSUE TITLE
link all modules in `learning/` to the kgc curriculum

### ISSUE THREAD

**Issue by cogan-shimizu** [kastle-lab/cs7810-intro-to-ke#17]
link all modules in [`learning/`](https://github.com/kastle-lab/cs7810-intro-to-ke/blob/master/learning/readme.md) to the [kgc curriculum](https://github.com/KGConf/open-kg-curriculum/tree/master/curriculum/modules)

**Comment by antreac** [comment]
The link for kgc curriculum is broken! @cogan-shimizu

**Comment by cogan-shimizu** [comment]
should be fixed now
